import { createContext, useContext, type ReactNode } from "react";

export type Language = "pt" | "en";
const translations: Record<string, string> = {
  "Abertura": "Opening",
  "Apresentação": "Presentation",
  "Arquitetura": "Architecture",
  "Conceitos": "Concepts",
  "Cenário": "Scenario",
  "Partida Direta": "Direct Starter",
  "Reversão": "Reversing",
  "Estrela-Triângulo": "Star-Delta",
  "Semáforo": "Traffic Light",
  "Encerramento": "Closing",
  "Final": "Summary",
  "PLC · Comandos Elétricos · IEC 61131-3": "PLC · Electrical Controls · IEC 61131-3",
  "SCADA é a camada de supervisão; o CLP é quem executa a lógica em ciclo determinístico": "SCADA provides supervision; the PLC executes the logic in a deterministic cycle",
  "Toda partida de motor precisa de selo, botão NF de parada e contato NF do térmico": "Motor starters use seal-in logic, a normally closed stop button and thermal overload protection",
  "Reversão exige intertravamento elétrico cruzado entre contatores (K1 ⊥ K2)": "Reversing requires cross-interlocking between contactors (K1 ⊥ K2)",
  "Estrela-Triângulo reduz a corrente de partida e depende de TON para comutar": "Star-delta reduces starting current and uses TON to change configurations",
  "Máquinas de estado (CASE) modelam sequências cíclicas como semáforos e batidas": "State machines (CASE) model cyclic sequences such as traffic lights and batches",
  "Structured Text e Ladder são equivalentes — o CLP traduz LD para a mesma lógica booleana": "Structured Text and Ladder can express the same Boolean control logic",
  "06 · Encerramento": "06 · Closing",
  "O que ficou": "Key takeaways",
  "Próximos passos": "Next steps",
  "Alarmes e Históricos": "Alarms and History",
  "Receitas e MES": "Recipes and MES",
  "Integre o CLP a um SCADA real e leia os tags via rede industrial.": "Connect the PLC to a real SCADA and read tags over an industrial network.",
  "Trate eventos críticos, registre tendências e gere relatórios.": "Handle critical events, record trends and generate reports.",
  "Eleve a automação ao nível 3 — produção orientada a ordem.": "Take automation to level 3 — order-driven production.",
  "Sistema · Online": "System · Online",
  "[OK] Demonstração concluída sem alarmes": "[OK] Presentation complete",
  "[OK] 4 cenários executados · 0 falhas": "[OK] 4 simulation scenarios available",
  "[END] Obrigado — pronto para perguntas.": "[END] Thank you.",
  "Camada de supervisão — exibe sinópticos, alarmes, históricos e permite ao operador interagir com o processo.": "Supervisory layer — displays process diagrams, alarms and history, and lets the operator interact with the process.",
  "Controlador Lógico Programável": "Programmable Logic Controller",
  "Executa a lógica de controle em ciclo determinístico: lê entradas, processa o programa e escreve saídas.": "Executes control logic in a deterministic cycle: reads inputs, processes the program and writes outputs.",
  "Rede industrial que transporta os tags entre CLP, IHM, SCADA e dispositivos remotos.": "Industrial network carrying tags between the PLC, HMI, SCADA and remote devices.",
  "I/O e Comandos": "I/O and Controls",
  "Botoeiras, contatoras, sensores": "Pushbuttons, contactors, sensors",
  "Os comandos elétricos clássicos — NA, NF, selo e intertravamento — são a base da automação.": "Classic electrical controls — NO, NC, seal-in and interlocking — form the basis of automation.",
  "01 · Arquitetura": "01 · Architecture",
  "Do botão à supervisão": "From pushbutton to supervision",
  "Pirâmide da automação · ISA-95": "Automation pyramid · ISA-95",
  "Sensores / Atuadores": "Sensors / Actuators",
  "04 · Cenário": "04 · Scenario",
  "Partida Estrela-Triângulo": "Star-Delta Starter",
  "Temporizador TON comuta a configuração após 5 segundos": "A TON timer changes the configuration after 5 seconds",
  "T1 · Temporizador": "T1 · Timer",
  "K1 · Linha": "K1 · Line",
  "S0 · Parar": "S0 · Stop",
  "S1 · Partir": "S1 · Start",
  "S1 · Ligar": "S1 · Start",
  "S1 · Direto": "S1 · Forward",
  "S2 · Reverso": "S2 · Reverse",
  "Etapa": "Stage",
  "ESTRELA": "STAR",
  "TRIÂNGULO": "DELTA",
  "HMI · Partida Y-Δ": "HMI · Y-Δ Starter",
  "SCADA · PLC · Comandos Elétricos": "SCADA · PLC · Electrical Controls",
  "Automação Industrial": "Industrial Automation",
  "ao vivo": "live",
  ", com código real.": ", with real code.",
  "Uma apresentação interativa de SCADA e CLP aplicada a comandos elétricos. Acione botoeiras, observe a lógica ladder energizar em tempo real e leia o código IEC 61131-3 que executa por trás de cada acionamento.": "An interactive SCADA and PLC presentation for electrical controls. Explore motor starters, live ladder logic and IEC 61131-3 code.",
  "Cenários": "Scenarios",
  "Interativo": "Interactive",
  "Linguagens": "Languages",
  "Tempo real": "Real time",
  "Simulação": "Simulation",
  "Selo + intertravamento térmico": "Seal-in logic + thermal interlocking",
  "HMI · Painel de Comando": "HMI · Control Panel",
  "HMI · Painel": "HMI · Panel",
  "Diagrama Ladder · Online Monitor": "Ladder Diagram · Online Monitor",
  "Modo": "Mode",
  "· Cenário": "· Scenario",
  "03 · Cenário": "03 · Scenario",
  "Reversão de Motor": "Motor Reversing",
  "Intertravamento elétrico — K1 bloqueia K2 e vice-versa": "Electrical interlocking — K1 blocks K2 and vice versa",
  "05 · Cenário": "05 · Scenario",
  "Semáforo Sequencial": "Sequential Traffic Light",
  "Máquina de estados (CASE) com temporizador único reaproveitado": "State machine (CASE) with a single reusable timer",
  "FASE": "PHASE",
  "HMI · Cruzamento": "HMI · Intersection",
  "Estado": "State",
  "Ciclo": "Cycle",
  "linhas · IEC 61131-3": "lines · IEC 61131-3",
  "● Compilado · Online": "● Simulation · Online",
  "Perfil de brunnodev": "brunnodev profile",
  "Iniciar apresentação": "Start presentation",
  "Explorar cenários": "Explore scenarios",
  "Anterior": "Previous",
  "Próximo": "Next",
  "Idioma": "Language",
  "Apresentação SCADA": "SCADA presentation",
  "Fluxo de sinal": "Signal flow",
  "Enviar sinal": "Send signal",
  "Limpar sinal": "Clear signal",
  "Entrada": "Input",
  "Programa": "Program",
  "Saída": "Output",
  "Supervisão": "Supervision",
  "Sinal recebido": "Signal received",
  "Aguardando sinal": "Waiting for signal",
  "Ler entradas": "Read inputs",
  "Executar lógica": "Execute logic",
  "Atualizar saídas": "Update outputs",
  "Ciclo de varredura": "Scan cycle",
  "Segurança": "Safety",
  "Simulação educacional — não conectada a um CLP físico.": "Educational simulation — not connected to a physical PLC.",
  "Planejamento empresarial, pedidos e recursos.": "Business planning, orders and resources.",
  "Execução da produção, receitas e rastreabilidade.": "Production execution, recipes and traceability.",
  "Supervisão do processo, alarmes e tendências.": "Process supervision, alarms and trends.",
  "Controle determinístico e processamento da lógica.": "Deterministic control and logic processing.",
  "Medição física e acionamento dos equipamentos.": "Physical measurement and equipment actuation.",
  "Proteções físicas e intertravamentos devem ser validados antes de qualquer aplicação real.": "Physical protections and interlocks must be validated before any real application."
};
const LanguageContext = createContext<Language>("pt");
export function LanguageProvider({ language, children }: { language: Language; children: ReactNode }) {
  return <LanguageContext.Provider value={language}>{children}</LanguageContext.Provider>;
}
export function useLanguage() {
  const language = useContext(LanguageContext);
  return { language, t: (text: string) => language === "en" ? translations[text] ?? text : text };
}
